name: release
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: go-semantic-release/action@v1
      id: semrel
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        changelog-generator-opt: "emojis=true"
