name: "Execution Plan on main"
'on':
  push:
    tags-ignore:
      - "**"
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      trigger: main

  execution-plan:
    uses: ./.github/workflows/execution-plan-snippet.yml
    with:
      trigger: main
    secrets: inherit

  integration-tests:
    needs: [execution-plan]
    uses: ./.github/workflows/integration-tests.yml
    with:
      trigger: main

